[package]
name = "tp-note"
version = "0.9.3"
authors = ["Jens Getreu <getreu@web.de>"]
edition = "2018"
readme = "README.md"
description = "fast note-takingg with templates and filename synchronization"
license = "MIT/Apache-2.0"
categories = ["command-line-utilities", "template-engine", "text-processing"]
documentation = "https://blog.getreu.net/projects/tp-note/tp-note--manpage.html"
homepage = "https://blog.getreu.net/projects/tp-note/"
repository = "https://github.com/getreu/tp-note"


[package.metadata.deb]
maintainer = "Jens Getreu, <getreu@web.de>"
copyright = "2015-2020, Jens Getreu <getreu@web.de>"
depends = "$auto"
extended-description = '''
tp-note is a note-taking-tool and a template system, that consistently
synchronizes the note’s meta-data with its filename. tp-note collects various
information about its environment and the clipboard and stores them in
variables. New notes are created by filling these variables in predefined and
customizable “Tera”-templates. In case the postional command-line-parameter
“<path>” points to an existing “tp-note”-file, the note’s meta-data is analysed
and, if necessary, its filename is modified. For all other file types, tp-note
creates a new note that annotates the file “<path>” points to. If “<path>” is a
directory (or, when omitted the current working directory), a new note is
created in that directory. After creation, tp-note launches an external editor
of your choice. Although the note’s structure follows “pandoc”-conventions, it
is not tied to any specific markup language.
'''
assets = [
    ["doc/build/html/index.html", "usr/share/doc/tp-note/", "644"],
    ["doc/build/pdf/tp-note--manpage.pdf", "usr/share/doc/tp-note/", "644"],
    ["doc/build/pdf/tp-note--manual.pdf", "usr/share/doc/tp-note/", "644"],
    ["doc/build/man/man1/tp-note.1.gz", "usr/share/man/man1/", "644"],
    ["target/release/tp-note", "usr/bin/tp-note", "755"]
]

[dependencies]
serde = { version = "1.0.104", features = ["derive"] }
serde_yaml = "0.8.11"
serde_json = "1.0.48"
anyhow = "1.0.26"
argh = "0.1.3"
lazy_static = "1.4.0"
chrono = "0.4.11"
time = "0.2.7"
#confy = { git = "https://github.com/getreu/confy" }
## https://github.com/rust-cli/confy/issues/11
## in  confy = "0.3.1"
confy = "0.3.1"

# On Linux you need the x11 library, install it with something like:
#    sudo apt-get install xorg-dev
clipboard = "0.5.0"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.8", features = ["winuser"] }

[dependencies.tera]
version = "1.1.0"
default-features = true 
