[package]
name = "tp-note"
version = "1.12.0"
authors = ["Jens Getreu <getreu@web.de>"]
edition = "2018"
readme = "README.md"
description = "Minimalist note taking: edit and save your clipboard content as a note file"
license = "MIT/Apache-2.0"
categories = ["command-line-utilities", "template-engine", "text-processing"]
documentation = "https://blog.getreu.net/projects/tp-note/tp-note--manual.html"
homepage = "https://blog.getreu.net/projects/tp-note/"
repository = "https://gitlab.com/getreu/tp-note"
build =  "build.rs"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.11"

[package.metadata.deb]
maintainer = "Jens Getreu, <getreu@web.de>"
copyright = "2015-2020, Jens Getreu <getreu@web.de>"
depends = "$auto"
extended-description = '''
tp-note is a note-taking-tool and a template system, that consistently
synchronizes the note’s meta-data with its filename. tp-note collects various
information about its environment and the clipboard, and stores them in
variables. New notes are created by filling these variables in predefined and
customizable “Tera”-templates. In case the positional command-line-parameter
“<path>” points to an existing “tp-note”-file, the note’s meta-data is analysed
and, if necessary, its filename is modified. For all other file types, tp-note
creates a new note that annotates the file “<path>” points to. If “<path>” is a
directory (or, when omitted the current working directory), a new note is
created in that directory. After creation, tp-note launches an external editor
of your choice. Although the note’s structure follows “pandoc”-conventions, it
is not tied to any specific markup language.
'''
assets = [
    ["doc/build/html/index.html", "usr/share/doc/tp-note/", "644"],
    ["doc/build/pdf/tp-note--manpage.pdf", "usr/share/doc/tp-note/", "644"],
    ["doc/build/pdf/tp-note--manual.pdf", "usr/share/doc/tp-note/", "644"],
    ["doc/build/man/man1/tp-note.1.gz", "usr/share/man/man1/", "644"],
    ["target/release/tp-note", "usr/bin/tp-note", "755"],
    ["assets/tp-note.svg", "usr/share/pixmaps/", "644"]
]

[features]
# To disable features: `cargo build --no-default-features`
default = ["message-box", "viewer"]
# If you can do away with error message popup boxes (for example on a headless
# system), no GTK is required. In this case all error messages will appear on
# the console from where you started _Tp-Note_ in `stderr` only.
# Disable this feature if you do not want error message boxes.
message-box = ["msgbox"]
# Markdown renderer and viewer are optional too.
viewer = ["notify", "httparse", "pulldown-cmark", "rst_parser", "rst_renderer", "webbrowser", "rand", "httpdate", "percent-encoding", "url"]

[dependencies]
anyhow = "1.0.40"
atty = "0.2.14"
chrono = "0.4.19"
clap = "2.33.3"
clipboard = "0.5.0"
# clipboard: On Debian Linux you need to: sudo apt-get install xorg-dev
confy = "0.4.0"
directories = "3.0.1"
httparse = { version = "1.3.6", optional = true }
httpdate = { version = "1.0.0", optional = true }
lazy_static = "1.4.0"
log = "0.4.14"
# msgbox: On Debian Linux you need to: sudo apt-get install -y xorg-dev libxcb-xfixes0-dev libxcb-shape0-dev libgtk-3-dev
msgbox = { version = "0.6.0", optional = true }
notify = { version = "4.0.16", optional = true }
parse-hyperlinks = "0.20.0"
# parse-hyperlinks = { path = "../parse-hyperlinks/parse-hyperlinks" }
percent-encoding = { version = "2.1.0", optional = true }
pulldown-cmark = { version = "0.8.0", default-features = false, features = ["simd"], optional = true }
rand = { version = "0.8.3", optional = true }
rst_parser = { version = "0.4.0", optional = true }
rst_renderer = { version = "0.4.0", optional = true }
sanitize-filename-reader-friendly = "1.1.1"
# sanitize-filename-reader-friendly = { path = "../sanitize-filename-reader-friendly" }
semver = "0.11.0"
serde_json = "1.0.64"
serde = { version = "1.0.125", features = ["derive"] }
serde_yaml = "0.8.17"
structopt = "0.3.21"
tera = { version = "1.7.1", default-features = true }
time = "0.2.26"
url = { version = "2.2.1", optional = true }
webbrowser = { version = "0.5.5", optional = true }

[target.'cfg(windows)'.dependencies]
win32job = "1.0.1"

