# [PROJECT_DIR]/Cargo.toml
[workspace]
members = ["tpnote", "tpnote-lib"]
default-members = ["tpnote", "tpnote-lib"]

[workspace.package]
version = "1.19.8"
authors = ["Jens Getreu <getreu@web.de>"]
edition = "2021"
rust-version = "1.64.0"
readme = "README.md"
description = "Minimalistic note taking: save and edit your clipboard content as a note file"
license = "MIT/Apache-2.0"
categories = ["command-line-utilities", "template-engine", "text-processing"]
documentation = "https://blog.getreu.net/projects/tp-note/tpnote--manual.html"
homepage = "https://blog.getreu.net/projects/tp-note/"
repository = "https://gitlab.com/getreu/tp-note"

[profile.release]
strip = "symbols"

[workspace.dependencies]
lazy_static = "1.4.0"
log = { version = "0.4.17", features = ["serde"] }
sanitize-filename-reader-friendly = "2.2.1"
serde = { version = "1.0.147", features = ["derive"] }
serde_yaml = "0.9.14"
thiserror = "1.0.37"
