[package]
authors.workspace = true
categories.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "tpnote-lib"
readme = "README.md"
repository.workspace = true
rust-version.workspace = true
version = "0.28.2"

[features]
default = ["renderer", "viewer", "lang-detection"]
renderer = ["dep:pulldown-cmark", "dep:rst_parser", "dep:rst_renderer", "dep:latex2mathml", "dep:syntect"]
lang-detection = ["dep:lingua"]
viewer = []

[dependencies]
html-escape = "0.2.13"
lazy_static.workspace = true
lingua = { version = "1.5.0", optional = true }
log.workspace = true
#parse-hyperlinks = { path = "../../parse-hyperlinks/parse-hyperlinks" }
parse-hyperlinks = "0.26.2"
# Plain text renderer.
#parse-hyperlinks-extras = { path = "../../parse-hyperlinks/parse-hyperlinks-extras" }
parse-hyperlinks-extras = "0.26.2"
percent-encoding = "2.3.0"
# Markdown renderer.
pulldown-cmark = { version = "0.9.3", default-features = false, features = ["simd"], optional = true }
latex2mathml = { version = "0.2.3", optional = true }
parking_lot.workspace = true
syntect = { version = "5.1.0", optional = true }
# ReStructuredText renderer.
rst_parser = { version = "0.4.0", optional = true }
# ReStructuredText renderer.
rst_renderer = { version = "0.4.0", optional = true }
sanitize-filename-reader-friendly.workspace = true
self_cell = "1.0.1"
serde_json = "1.0.107"
serde.workspace = true
serde_yaml.workspace = true
substring = "1.4.5"
tera.workspace = true
thiserror.workspace = true
toml.workspace = true


[target.'cfg(windows)'.dependencies]
win32job = "1.0.2"
windows-sys = { version = "0.48.0", features = [
         #"Win32_Foundation",
         #"Win32_Security",
         #"Win32_System_Threading",
         #"Win32_UI_WindowsAndMessaging",
         "Win32_Globalization",
         "Win32_System_SystemServices",
     ] }
