[package]
authors.workspace = true
categories.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "tpnote-lib"
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version = "0.13.0"

[features]
default = ["renderer", "viewer"]
renderer = ["pulldown-cmark", "cmark-syntax", "rst_parser", "rst_renderer"]
viewer = ["percent-encoding"]

[dependencies]
cmark-syntax = { version = "0.3.1", features = ["latex2mathml"], optional = true }
lazy_static.workspace = true
log.workspace = true
parse-hyperlinks = "0.23.4"
parse-hyperlinks-extras = "0.23.4"
# parse-hyperlinks = { path = "../parse-hyperlinks/parse-hyperlinks" }
percent-encoding = { version = "2.2.0", optional = true }
pulldown-cmark = { version = "0.9.2", default-features = false, features = ["simd"], optional = true }
rst_parser = { version = "0.4.0", optional = true }
rst_renderer = { version = "0.4.0", optional = true }
sanitize-filename-reader-friendly.workspace = true
self_cell = "0.10.2"
serde_json = "1.0.89"
serde.workspace = true
serde_yaml.workspace = true
substring = "1.4.5"
tera = { version = "1.17.1", default-features = true }
thiserror.workspace = true
toml = "0.5.9"


[target.'cfg(windows)'.dependencies]
win32job = "1.0.2"

[dependencies.windows-sys]
version = "0.42.0"
features = [
    #"Win32_Foundation",
    #"Win32_Security",
    #"Win32_System_Threading",
    #"Win32_UI_WindowsAndMessaging",
    "Win32_Globalization",
    "Win32_System_SystemServices",
]
