[package]
authors.workspace = true
categories.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "tpnote-lib"
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version = "0.19.1"

[features]
# Exclude "renderer-extras" to stay in _MIT/Apache_ license and the avoid additional
# _GPL-3.0-or-laterGPL-3.0-or-later_ license.
default = ["renderer", "viewer", "lang-detection"]
renderer = ["pulldown-cmark", "rst_parser", "rst_renderer", "latex2mathml", "syntect"]
lang-detection = ["lingua"]
viewer = []

[dependencies]
lazy_static.workspace = true
lingua = { version = "1.4.0", optional = true }
log.workspace = true
parse-hyperlinks = "0.23.4"
parse-hyperlinks-extras = "0.23.4"
# parse-hyperlinks = { path = "../parse-hyperlinks/parse-hyperlinks" }
percent-encoding = "2.2.0"
pulldown-cmark = { version = "0.9.2", default-features = false, features = ["simd"], optional = true }
latex2mathml = { version = "0.2.3", optional = true }
syntect = { version = "5.0.0", optional = true }
rst_parser = { version = "0.4.0", optional = true }
rst_renderer = { version = "0.4.0", optional = true }
sanitize-filename-reader-friendly.workspace = true
self_cell = "0.10.2"
serde_json = "1.0.96"
serde.workspace = true
serde_yaml.workspace = true
substring = "1.4.5"
tera = { version = "1.18.1", default-features = true }
thiserror.workspace = true
toml.workspace = true


[target.'cfg(windows)'.dependencies]
win32job = "1.0.2"
windows-sys = { version = "0.48.0", features = [
         #"Win32_Foundation",
         #"Win32_Security",
         #"Win32_System_Threading",
         #"Win32_UI_WindowsAndMessaging",
         "Win32_Globalization",
         "Win32_System_SystemServices",
     ] }
