[package]
name = "tpnote-html2md"
version = "0.2.15"
edition = "2018"
authors = ["Oleg `Kanedias` Chernovskiy <kanedias@house-of-maker.online>",
           "Jens Getreu <getreu@web.de>"]

description = "HTML to Markdown converter library"
repository = "https://gitlab.com/getreu/tpnote-html2md"
readme = "README.md"
keywords = ["html", "markdown", "converter"]
categories = ["development-tools", "parsing", "parser-implementations"]
license = "MIT"


[lib]
name = "html2md"
#target_env="musl"crate-type = ["rlib", "dylib", "staticlib"]

[dependencies]
html5ever = "0.27.0"
markup5ever_rcdom = "0.3.0"
regex = "1.11.1"
percent-encoding = "2.3.1"

[dev-dependencies]
indoc = "2.0.5"

# [profile.release]
# debug = false
# lto = true
# panic = 'abort'

# To use this project on Android we need JNI
[target.'cfg(target_os="android")'.dependencies]
jni = { version = "0.21.1", default-features = false }
